# Sample .travis.yml for R projects

language: r

compiler:
    - gcc

os:
    - linux

before_script:
  - sudo add-apt-repository ppa:apokluda/boost1.53
  - sudo apt-get update
  - sudo apt-get install libboost1.53-all-dev

addons:
  apt:
    sources:
      - boost-1.53
    packages:
      - libboost1.53-all-dev

warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
