# Sample .travis.yml for R projects

language: r, cpp
compiler:
    - gcc
os:
    - linux

addons:
  apt:
    sources:
      - boost
    packages:
      - libboost
      - cmake


warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
