# Sample .travis.yml for R projects

language: 
    - r
    - cpp

compiler:
    - g++

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-all-dev
      - cmake

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq install g++-4.8
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="g++-4.8";
      export CXX="g++-4.8";
      export LINK="g++-4.8";
      export LINKXX="g++-4.8";
    fi
  - g++ --version

warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

