
language: 
    - r
    - cpp

compiler:
    - gcc

os:
    - linux

warnings_are_errors: false
sudo: required

addons:
  apt:
    sources:
    packages:
      - cmake

before_script:
  - sudo add-apt-repository ppa:apokluda/boost1.53
  - sudo apt-get update
  - sudo apt-get install libboost1.53-all-dev

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

