# Sample .travis.yml for R projects

language: 
    - r
    - cpp

compiler:
    - gcc

os:
    - linux

addons:
  apt:
    sources:
      - boost-latest
    packages:
<<<<<<< Updated upstream
      - libboost1.53-all-dev
=======
<<<<<<< HEAD
      - libboost-all-dev
      - cmake
=======
      - libboost1.53-all-dev
>>>>>>> origin/master

before_script:
  - sudo add-apt-repository ppa:apokluda/boost1.53
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.53-all-dev
>>>>>>> Stashed changes

warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

